# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Spring Boot CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  id-token: write
  security-events: write
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Debug Secrets (except token!)
        run: |
          if [ -z "${{ secrets.SONARTOKENNEW }}" ]; then echo "SONAR_TOKEN is empty"; else echo "SONAR_TOKEN is set"; fi
          if [ -z "${{ secrets.SONAR_PROJECT_KEY }}" ]; then echo "SONAR_PROJECT_KEY is empty"; else echo "SONAR_PROJECT_KEY is set"; fi
          if [ -z "${{ secrets.SONAR_ORGANIZATION }}" ]; then echo "SONAR_ORGANIZATION is empty"; else echo "SONAR_ORGANIZATION is set"; fi

      - name: Build and analyze with SonarCloud
        run: |
          mvn clean verify sonar:sonar \
            -DskipTests=true \
            -Dsonar.projectKey=TechVisionaries_AuthenticationService \
            -Dsonar.organization=techvisionaries \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=79f5c1145c09831ac4c867c64246c9666f5896b6

      # - name: Update dependency graph
      #   uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

      - name: Build Spring Boot JAR
        run: mvn clean package -DskipTests
        
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: osadhaog
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t osadhaog/auth-microservice:latest .
          docker push osadhaog/auth-microservice:latest
